import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeModeScript } from "flowbite-react";
import "./globals.css";
import  StoreProvider from '@/app/redux/storeProvider'
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Flowbite React",
  description: "Generated by create flowbite react",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body className={inter.className}>
              <StoreProvider>
               {children}
             </StoreProvider>

        
        </body>
    </html>
  );
}



// import '@/styles/globals.scss'
// import { config } from '@fortawesome/fontawesome-svg-core'
// import '@fortawesome/fontawesome-svg-core/styles.css'
// import ProgressBar from '@/components/ProgressBar/ProgressBar'
// import DictionaryProvider from '@/locales/DictionaryProvider'
// import { getDictionary } from '@/locales/dictionary'
// import getTheme from '@/themes/theme'
// import { Provider } from 'react-redux'
// import { PersistGate } from 'redux-persist/integration/react'
// import persistStore from 'redux-persist/es/persistStore'
// import StoreProvider from '@/redux/storeProvider'

// // You change this configuration value to false so that the Font Awesome core SVG library
// // will not try and insert <style> elements into the <head> of the page.
// // Next.js blocks this from happening anyway so you might as well not even try.
// // See https://fontawesome.com/v6/docs/web/use-with/react/use-with#next-js
// config.autoAddCss = false

// // store to persist
// // const persistedStore = persistStore(store)
// // const helmetContext = {}

// export default async function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   const dictionary = await getDictionary()

//   return (
//     <html lang="en" data-bs-theme={getTheme()}>
//           <body>
//             <ProgressBar />
//             <DictionaryProvider dictionary={dictionary}>
//               <StoreProvider>
//               {children}
//               </StoreProvider>
              
//             </DictionaryProvider>
//           </body>
       
//     </html>
//   )
// }